name: McpeServerHackingPlugin
main: MC\PE\Main
version: 2.0.0
api: 
 - 3.0.0-ALPHA12
 - 3.0.0-ALPHA11
 - 3.0.0-ALPHA10
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA8
 - 3.0.0-ALPHA7
 - 3.0.0-ALPHA6
 - 3.0.0-ALPHA5
 - 3.0.0
 - 2.0.0
 - 1.0.0
